# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 382169725a56707b051afa83f65facf21d85288b002614105e061bf4536382c0498d39dc974c4db52118aaa5316e6cdf55b6209f49272939eb962dec441e06f8

test:
  secret_key_base: 18f42209cf5b21ef75561fe980fd2ac04f19124cdd1654074b53ab9290e4020923e0a2146b25b2d8e70cca5a20d62f08959ca73f5ea1fe84c001fe365093b530

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
